In [1]:
import sys
print(sys.executable)

/Users/chris/Documents/Visual Studio Code/projects/football_ml_api/venv/bin/python

In [3]:
import pandas as pd

df = pd.read_csv('../data/raw/laliga_matches_20260529_093613.csv')

In [33]:
df.head(10)

,match_id,country,competition,utc_date,status,season_start_year,matchday,home_team,away_team,home_goals,away_goals,winner,referee
0,438482,Spain,Primera Division,2023-08-11 17:30:00+00:00,FINISHED,2023,1,UD Almería,Rayo Vallecano de Madrid,0,2,AWAY_TEAM,Javier Alberola Rojas
1,438479,Spain,Primera Division,2023-08-11 20:00:00+00:00,FINISHED,2023,1,Sevilla FC,Valencia CF,1,2,AWAY_TEAM,José Sánchez Martínez
2,438481,Spain,Primera Division,2023-08-12 15:00:00+00:00,FINISHED,2023,1,Real Sociedad de Fútbol,Girona FC,1,1,DRAW,Francisco Hernández Maeso
3,438483,Spain,Primera Division,2023-08-12 17:30:00+00:00,FINISHED,2023,1,UD Las Palmas,RCD Mallorca,1,1,DRAW,Víctor García Verdura
4,438474,Spain,Primera Division,2023-08-12 19:30:00+00:00,FINISHED,2023,1,Athletic Club,Real Madrid CF,0,2,AWAY_TEAM,Jesús Gil Manzano
5,438476,Spain,Primera Division,2023-08-13 15:00:00+00:00,FINISHED,2023,1,RC Celta de Vigo,CA Osasuna,0,2,AWAY_TEAM,Pablo González Fuertes
6,438480,Spain,Primera Division,2023-08-13 17:30:00+00:00,FINISHED,2023,1,Villarreal CF,Real Betis Balompié,1,2,AWAY_TEAM,Miguel Ortiz Arias
7,438478,Spain,Primera Division,2023-08-13 19:30:00+00:00,FINISHED,2023,1,Getafe CF,FC Barcelona,0,0,DRAW,César Soto Grado
8,438477,Spain,Primera Division,2023-08-14 17:30:00+00:00,FINISHED,2023,1,Cádiz CF,Deportivo Alavés,1,0,HOME_TEAM,Isidro Díaz de Mera
9,438475,Spain,Primera Division,2023-08-14 19:30:00+00:00,FINISHED,2023,1,Club Atlético de Madrid,Granada CF,3,1,HOME_TEAM,Juan Pulido Santana

In [29]:
print("Total partidos:", df.shape[0])

Total partidos: 1140

In [32]:
print("Temporadas únicas:", df['season_start_year'].nunique(), "->", df['season_start_year'].unique())

Temporadas únicas: 3 -> [2023 2024 2025]

In [41]:
print("Competiciones únicas:", df['competition'].unique()[0])

Competiciones únicas: Primera Division

In [48]:
equipos = df['home_team'].unique()
print("Equipos únicos:")
for equipo in equipos:
    print(equipo)

Equipos únicos:
UD Almería
Sevilla FC
Real Sociedad de Fútbol
UD Las Palmas
Athletic Club
RC Celta de Vigo
Villarreal CF
Getafe CF
Cádiz CF
Club Atlético de Madrid
RCD Mallorca
Valencia CF
CA Osasuna
Girona FC
FC Barcelona
Real Betis Balompié
Deportivo Alavés
Granada CF
Rayo Vallecano de Madrid
Real Madrid CF
Real Valladolid CF
RCD Espanyol de Barcelona
CD Leganés
Elche CF
Levante UD
Real Oviedo

In [51]:
print("Columnas:", df.columns)

Columnas: Index(['match_id', 'country', 'competition', 'utc_date', 'status',
       'season_start_year', 'matchday', 'home_team', 'away_team', 'home_goals',
       'away_goals', 'winner', 'referee'],
      dtype='str')

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1140 entries, 0 to 1139
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           1140 non-null   int64
 1   country            1140 non-null   str
 2   competition        1140 non-null   str
 3   utc_date           1140 non-null   str
 4   status             1140 non-null   str
 5   season_start_year  1140 non-null   int64
 6   matchday           1140 non-null   int64
 7   home_team          1140 non-null   str
 8   away_team          1140 non-null   str
 9   home_goals         1140 non-null   int64
 10  away_goals         1140 non-null   int64
 11  winner             1140 non-null   str
 12  referee            1140 non-null   str
dtypes: int64(5), str(8)
memory usage: 115.9 KB

In [53]:
df.isna().sum()

match_id             0
country              0
competition          0
utc_date             0
status               0
season_start_year    0
matchday             0
home_team            0
away_team            0
home_goals           0
away_goals           0
winner               0
referee              0
dtype: int64

In [55]:
df['winner'].value_counts()

winner
HOME_TEAM    522
AWAY_TEAM    321
DRAW         297
Name: count, dtype: int64

In [60]:
print("Goles por partido:", (df['home_goals'].sum() + df['away_goals'].sum()) / df.shape[0])

Goles por partido: 2.6526315789473682

In [64]:
df.loc[(df['home_goals'] + df['away_goals']) < 2]

,match_id,country,competition,utc_date,status,season_start_year,matchday,home_team,away_team,home_goals,away_goals,winner,referee
7,438478,Spain,Primera Division,2023-08-13 19:30:00+00:00,FINISHED,2023,1,Getafe CF,FC Barcelona,0,0,DRAW,César Soto Grado
8,438477,Spain,Primera Division,2023-08-14 17:30:00+00:00,FINISHED,2023,1,Cádiz CF,Deportivo Alavés,1,0,HOME_TEAM,Isidro Díaz de Mera
10,438491,Spain,Primera Division,2023-08-18 17:30:00+00:00,FINISHED,2023,2,RCD Mallorca,Villarreal CF,0,1,AWAY_TEAM,Javier Alberola Rojas
11,438490,Spain,Primera Division,2023-08-18 19:30:00+00:00,FINISHED,2023,2,Valencia CF,UD Las Palmas,1,0,HOME_TEAM,Javier Iglesias Villanueva
17,438484,Spain,Primera Division,2023-08-20 19:30:00+00:00,FINISHED,2023,2,Real Betis Balompié,Club Atlético de Madrid,0,0,DRAW,Ricardo de Burgos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1122,544574,Spain,Primera Division,2026-05-17 17:00:00+00:00,FINISHED,2025,37,Elche CF,Getafe CF,1,0,HOME_TEAM,Víctor García Verdura
1126,544578,Spain,Primera Division,2026-05-17 17:00:00+00:00,FINISHED,2025,37,Real Oviedo,Deportivo Alavés,0,1,AWAY_TEAM,José Munuera Montero
1128,544580,Spain,Primera Division,2026-05-17 17:00:00+00:00,FINISHED,2025,37,Sevilla FC,Real Madrid CF,0,1,AWAY_TEAM,José Sánchez Martínez
1132,544583,Spain,Primera Division,2026-05-23 19:00:00+00:00,FINISHED,2025,38,RC Celta de Vigo,Sevilla FC,1,0,HOME_TEAM,Francisco Hernández Maeso
1134,544585,Spain,Primera Division,2026-05-23 19:00:00+00:00,FINISHED,2025,38,Getafe CF,CA Osasuna,1,0,HOME_TEAM,Alejandro Quintero González

In [72]:
victorias = {}

for _, partido in df.iterrows():
    if partido['winner'] == 'HOME_TEAM':
        victorias[partido['home_team']] = victorias.get(partido['home_team'], 0) + 1

    elif partido['winner'] == 'AWAY_TEAM':
        victorias[partido['away_team']] = victorias.get(partido['away_team'], 0) + 1

equipo_mas_victorias = max(victorias, key=victorias.get)

print(f"Equipo con más victorias: {equipo_mas_victorias}")
print(f"Victorias: {victorias[equipo_mas_victorias]}")

Equipo con más victorias: FC Barcelona
Victorias: 85

In [73]:
df.head()

,match_id,country,competition,utc_date,status,season_start_year,matchday,home_team,away_team,home_goals,away_goals,winner,referee
0,438482,Spain,Primera Division,2023-08-11 17:30:00+00:00,FINISHED,2023,1,UD Almería,Rayo Vallecano de Madrid,0,2,AWAY_TEAM,Javier Alberola Rojas
1,438479,Spain,Primera Division,2023-08-11 20:00:00+00:00,FINISHED,2023,1,Sevilla FC,Valencia CF,1,2,AWAY_TEAM,José Sánchez Martínez
2,438481,Spain,Primera Division,2023-08-12 15:00:00+00:00,FINISHED,2023,1,Real Sociedad de Fútbol,Girona FC,1,1,DRAW,Francisco Hernández Maeso
3,438483,Spain,Primera Division,2023-08-12 17:30:00+00:00,FINISHED,2023,1,UD Las Palmas,RCD Mallorca,1,1,DRAW,Víctor García Verdura
4,438474,Spain,Primera Division,2023-08-12 19:30:00+00:00,FINISHED,2023,1,Athletic Club,Real Madrid CF,0,2,AWAY_TEAM,Jesús Gil Manzano